### ISSUE TITLE
Quantized latents are not used at all?

### ISSUE THREAD

**Issue by inspirit** [lucidrains/titok-pytorch#1]
Hi Phil,
are you sure that we pass original latents to decoder instead of quantized?
https://github.com/lucidrains/titok-pytorch/blob/8e56054a9306edcab4643f5c6279ca4061057581/titok_pytorch/titok.py#L185

i looked through the paper and they decode using mask tokens + quantized latents

**Comment by lucidrains** [comment]
@inspirit hey! thanks as usual 😄
